### ISSUE TITLE
a special bitch for mac users.

### ISSUE THREAD

**Issue by xDidntPot** [Noxiuam/Bitches#15]

**Comment by Noxiuam** [comment]
I believe it’s time I do this.

**Comment by xDidntPot** [comment]
oh yes.

**Comment by Noxiuam** [comment]
What do you propose I name this bitch?

**Comment by xDidntPot** [comment]
upto you >w<

**Comment by Noxiuam** [comment]
@xDidntPot done. Join the support discord for more bitches. https://discord.gg/3rrXMj6caE
