### ISSUE TITLE
Add a kitten bitch for *BSD users

### ISSUE THREAD

**Issue by dotslashlevi** [Noxiuam/Bitches#17]
They say linux is bloated when in reality they are after jizzing 400 times and eating 50lb of food a day.

**Comment by Noxiuam** [comment]
This is being added NOW.

**Comment by Noxiuam** [comment]
https://github.com/Noxiuam/Bitches/commit/26038a1013c2f691a7b7382c09fc43f7b47e4609

**Comment by dotslashlevi** [comment]
LOL
