### ISSUE TITLE
skill issue

### ISSUE THREAD

**Issue by nxtdaydelivery** [Noxiuam/Bitches#18]
ahem please replace new Random().next repeated calls with a private static final random for the usage of the random methods.
this will improve its performance so I can run it on my grandma's toaster (remember, 3 billion devices run Java)

**Comment by Noxiuam** [comment]
yes yes i do in fact remember this!

**Comment by Noxiuam** [comment]
it has NOW been resolved.............................................. you have been granted 50 times the amount of bitches of a normal user!
