### ISSUE TITLE
femboy bitch skin for JavaOS users.

### ISSUE THREAD

**Issue by GenericRat** [Noxiuam/Bitches#19]
i don't know if femboys are considered bitches but there's 2 ways to know, 1 is taking this as denied, 2 is googling it up which held no actual answer sooo... i also need to change my pfp, now i'm literally commenting on myself lol... funny i said lol since a long time, ig i'm too traumatized of League Of Legends(never played it tho, and i never will).

**Comment by therealnv6** [comment]
Hii~~

I fixie wixied the JSON-api fucksy wucksie!!! xpp

I repwaced the `Prototypes.func` wiff a more ~streamylined~ kawaii `Pwototypiee.funkywunks` object that makes the JS go sooper dooper fast!! xD *starts twerking*

Can u pwease merge my pwull wequest senpai?!! UwU

**Comment by Noxiuam** [comment]
What the fuck

**Comment by Noxiuam** [comment]
what in the name of fuck

**Comment by GenericRat** [comment]
just go with it nox, just go with it... i'm as confused as u ar
