### ISSUE TITLE
Linux User

### ISSUE THREAD

**Issue by ProMaster420** [Noxiuam/Bitches#2]
Linux user should have no bitches!1!!!11!!

**Comment by he3als** [comment]
### Facts. Can confirm personally

**Comment by devrawr** [comment]
as a professional linuxer, this is only partially true. Arch users have no bitches, XeLinux users have all the bitches. 
![image](https://user-images.githubusercontent.com/96917554/160012877-34ea66a2-c285-4085-8560-23d10487d18c.png)

**Comment by Noxiuam** [comment]
_I shall add a new bitch type for Linux then_

**Comment by patrickzondervan** [comment]
thank you Noxiuam
