### ISSUE TITLE
Too much bitches

### ISSUE THREAD

**Issue by Thereallo1026** [Noxiuam/Bitches#7]
can't uncode the bitches
need fix

**Comment by jorgieee** [comment]
Help I got none

**Comment by apple171017** [comment]
this is a certified bitches moment

**Comment by Aetopia** [comment]
I need no bitches, being bitchless is best.

**Comment by Noxiuam** [comment]
**too bad**

**Comment by Noxiuam** [comment]
Simply turn your computer off as they are virtual.
